---
title: "Analyse Titanic"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(carData)

```

```{r}
head(TitanicSurvival)
```
```{r}
summary(TitanicSurvival)

```
```{r}
# Calcul des statistiques descriptives pour l'?ge
summary(TitanicSurvival$age)
```

```{r}
library(ggplot2)

```

```{r}
# Survivors' breakdown by sex and passenger class
ggplot(TitanicSurvival, aes(x = sex, fill = survived)) +
  geom_bar(position = "dodge") +
  facet_wrap(~passengerClass) +
  labs(title = "Survivors' breakdown by sex and passenger class", x = "Sex", y = "Number of survivors")  + theme(plot.title = element_text(hjust = 0.5))
```
```{r}
# Age of passengers based on survival
ggplot(TitanicSurvival, aes(x = survived, y = age, fill = survived)) +
  geom_violin(trim = FALSE, fill = "red", color = "red", alpha = 0.7) + 
  geom_boxplot(width = 0.1, fill = "red", color = "red", outlier.shape = NA) +  # Boxplot sans points aberrants
  labs(title = "Age distribution of passengers by survival", x = "survival
", y = "?ge") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values = c("no" = "red", "yes" = "blue")) +
  theme_minimal()
```

Interpretations des resultats

D'apres les du graphe 1